# Список RSS-лент (исключены украинские проекты).
FEEDS = {
    "Meduza": "https://meduza.io/rss/all",
    "The Insider": "https://theins.ru/feed",
    "iStories": "https://istories.media/feed",
    "Mediazona": "https://zona.media/rss",
    "Novaya Gazeta Europe": "https://novayagazeta.eu/feed",
    "Holod": "https://holod.media/feed",
    "DOXA": "https://doxajournal.ru/feed",
    "7x7": "https://7x7-journal.ru/rss",
    "RusNews": "https://rusnews.media/feed",
    "Verstka": "https://verstka.media/feed",
    "Agents.Media": "https://agents.media/feed",
    "Spektr": "https://spektr.press/feed",
    "The Bell": "https://thebell.io/feed",
    "Proekt": "https://www.proekt.media/feed",
    "Zerkalo": "https://www.zerkalo.io/feed",
    "Nasha Niva": "https://nashaniva.com/feed",
    "Euroradio": "https://euroradio.fm/rss",
    "Belsat": "https://belsat.eu/ru/feed",
    "OC Media": "https://oc-media.org/ru/feed",
    "Kloop": "https://kloop.kg/feed",
    "Fergana": "https://fergana.media/rss",
    "Re:Baltica": "https://en.rebaltica.lv/feed",
    "Bellingcat": "https://www.bellingcat.com/feed/",
}